### PR TITLE
Update the download buttons font size

### PR DESCRIPTION
**Pull request by nyaazi**
A somewhat hacky temporary fix untill a CSS master comes and makes something more permanent.

### CODE REVIEW

**Comment by sharkykh** [comment]
Why not use a `btn-xs` class (smaller button) on the report button you added? Since it's the one that's too big?

**Comment by Ricardo1991** [comment]
that actually seems the best

**Comment by sharkykh** [comment]
@Ricardo1991 
It does, but I think it still makes the row's height a little bit bigger. Can you check with DevTools/FireBug?

**Comment by nyaazi** [comment]
Because even before I thought the text is kinda small and the small report button looks silly to me,

**Comment by Ricardo1991** [comment]
@sharkykh Yes, with the small button it is still 2px taller, from the button padding

**Comment by ReimuHakurei** [comment]
Thoughts on this for the report button?

https://i.shoov.in/1496318594.png

**Comment by sharkykh** [comment]
@ReimuHakurei I like that it's the same style as the download links.
As for the icon, http://fontawesome.io/icon/flag/ feels more fitting.

**Comment by ReimuHakurei** [comment]
Ah, good point.

**Comment by sharkykh** [comment]
The [(first) report button in the help template](https://github.com/nyaadevs/nyaa/blob/master/nyaa/templates/help.html#L40) should also be changed to match whatever change this PR will end up doing.

**Comment by aldacron** [comment]
@ReimuHakurei I think fixing the report button should close this PR. The goal is to match the sizes, right?

**Comment by ReimuHakurei** [comment]
Changed to btn-xs for now. Will consider better options in the future.

**Pull request closed without merging**
