### PR TITLE
[Restructure routes 1] Import sorting + Static pages

### PR DESCRIPTION
**Pull request by sharkykh**
* Start sorting imports (one by one for now) - `isort path/to/file.py` (requires [`isort`](https://pypi.python.org/pypi/isort) to be installed in virtual environment)
* Start restructuring the `routes.py` file into smaller blueprint files.
  This is a suggestion... There might be a better way to go about this.
  Starting small, with the static routes:
    * /about (commented out)
    * /help
    * /rules
    * /xmlns/nyaa

### CODE REVIEW

**Comment by mreweilk** [comment]
I fully support cleaning up routes.py
Thanks for the hard work you've put in :)

**Comment by sharkykh** [comment]
@mreweilk I actually finished splitting everything into blueprints.
I just don't want [to make this PR huge...](https://user-images.githubusercontent.com/10238474/27982756-3687c7ba-63b4-11e7-8a22-0b001db0413d.png)

**Comment by mreweilk** [comment]
Can't wait to see it. We've been saying we would do something like this for a while now and no one ever got to it.

**Comment by Arylide** [comment]
That is indeed quite big. The work is much appreciated sharkykh.

**Comment by sharkykh** [comment]
@mreweilk 
You can if you want to :)
[Here ya go](https://github.com/nyaadevs/nyaa/compare/master...sharkykh:restruct-future)

**Comment by mreweilk** [comment]
You think this is ready for a pull request?

**Comment by sharkykh** [comment]
@mreweilk Don't think so. It still needs more testing to make sure I didn't miss anything.

**Comment by mreweilk** [comment]
This is a good start but let's wait for the finished one before doing anything with this.

**Comment by sharkykh** [comment]
K, so you want me to split it into sensibly-sized and tested PRs?

**Comment by mreweilk** [comment]
Yea that would be good. How about like user views in one torrent another etc?

**Comment by sharkykh** [comment]
@mreweilk So.. The plan I envisioned on IRC doesn't work as expected.
Maybe we should merge this and do what you suggested?
><matt> so basically 1 at a time
><matt> wait for it to get added
><matt> then the next one?

**Comment by sharkykh** [comment]
Oh, and this PR is tested, so it's ready.

**Pull request merged**
