### PR TITLE
Elasticsearch comment count

### PR DESCRIPTION
**Pull request by TheAMM**
*Note: schema and ES index are changed in these commits.*

This branch adds `comment_count` to the `Torrent` and Elasticsearch rows. It will allow us to search & sort by comment counts, and display the counts in search results like implemented in #169.

The field is recalculated on new and deleted comments.
Each Torrent has to have their comment_count calculated before reindexing ES!

### CODE REVIEW

**Comment by sharkykh** [comment]
@TheAMM 
The migration doesn't work for me, but maybe that's just because I'm using SQLite instead of MySQL?

<details><summary>Click here to see the logs</summary>

```
$ python db_migrate.py db upgrade
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade d0eeb8049623 -> 2bceb2cb4d7c, Add comment_count to Torrent
Traceback (most recent call last):
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: Cannot add a NOT NULL column with default value NULL

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "db_migrate.py", line 13, in <module>
    manager.run()
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/flask_migrate/__init__.py", line 244, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/alembic/script/base.py", line 421, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/alembic/util/compat.py", line 64, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "migrations/env.py", line 87, in <module>
    run_migrations_online()
  File "migrations/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/alembic/runtime/environment.py", line 817, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/alembic/runtime/migration.py", line 329, in run_migrations
    step.migration_fn(**kw)
  File "/cygdrive/c/Github/nyaa/migrations/versions/2bceb2cb4d7c_add_comment_count_to_torrent.py", line 21, in upgrade
    op.add_column('nyaa_torrents', sa.Column('comment_count', sa.Integer(), nullable=False))
  File "<string>", line 8, in add_column
  File "<string>", line 3, in add_column
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/alembic/operations/ops.py", line 1551, in add_column
    return operations.invoke(op)
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/alembic/operations/base.py", line 318, in invoke
    return fn(self, operation)
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/alembic/operations/toimpl.py", line 123, in add_column
    schema=schema
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/alembic/ddl/impl.py", line 172, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1002, in _execute_ddl
    compiled
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/cygdrive/c/Github/nyaa/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) Cannot add a NOT NULL column with default value NULL [SQL: 'ALTER TABLE nyaa_torrents ADD COLUMN comment_count INTEGER NOT NULL']
```
</details>

**Comment by TheAMM** [comment]
Sadly we dropped SQLite support a long time ago; the current SQLite is an outdated shim.

**Comment by sharkykh** [comment]
@TheAMM 
I think setting up MySQL with my configuration will be too difficult, so I'll probably stay with SQLite for now.

BTW, found a workaround by setting a default value. Changed [this line](https://github.com/nyaadevs/nyaa/blob/6c80557e39e7add5878a6fa4fb362cdf894a0c59/migrations/versions/2bceb2cb4d7c_add_comment_count_to_torrent.py#L21-L21) to
```python
op.add_column('nyaa_torrents', sa.Column('comment_count', sa.Integer(), nullable=False, server_default='0'))
```
and it seems to work with my pull request :+1:
The counts are displayed correctly, and the sorting works.
And when adding and deleting comments the count is updated.

**Comment by shm0o** [comment]
The migrations in the project are wrong in general anyway, so...

**Comment by TheAMM** [comment]
What's with your attitude, @shm0o? If shit's broke then go ahead and fix it or at the very least throw an issue on the tracker. You're now making me hold the better migrations hostage, because you'd otherwise think they were thanks to you.

**Comment by shm0o** [comment]
Uh, what? I already talked with nyaadev on irc about the migrations and stuff a while ago and we ended up agreeing it wasn't that trivial to fix because of the different table names per flavor; me saying stuff is wrong doesn't mean that I say that you're fucking shit up, but more like the workflow won't be as straightforward as we'd wanted it to be. Also don't say that as if I haven't tried to [contribute already](https://github.com/nyaadevs/nyaa/pull/194).

**Comment by TheAMM** [comment]
You're passive-aggressively bringing up the "migrations being wrong in general" in a PR that is not about the migrations. There's nothing wrong with the message, but the delivery is faulty. If you've already discussed them with @nyaadev, then you should know why they are sub-optimal, and your comment is not contributing anything in this thread.

**Comment by shm0o** [comment]
I was replying to @sharkykh though, because I assumed he/she doesn't know about the migrations stuff. With that said, If my comment still seems rude, well, I sincerely apologize.

**Pull request merged**
