### PR TITLE
Added Dark Mode to navbar #110

### PR DESCRIPTION
**Pull request by jhonnold**

### CODE REVIEW

**Comment by jhonnold** [comment]
Missed resizing problems

**Comment by jhonnold** [comment]
Oh, never mind that's always there sub-1200px

**Comment by aldacron** [comment]
Hmm, do you have a screenshot?

**Comment by jhonnold** [comment]
dark mode_1200

above 1200px for standard screens

dark mode_992

992px - 1200px for middle (The resizing issue is the search bar dropping down, however that's happening regardless of the "Dark Mode" text)

dark mode_mobile

below 992px for mobile

**Pull request closed without merging**
