### PR TITLE
Darkened success and danger colors for the dark theme

### PR DESCRIPTION
**Pull request by thebombzen**
This should make the dark theme more usable

### CODE REVIEW

**Comment by thebombzen** [comment]
Wow, okay, how did I miss that. Okay. Will do.

**Comment by Ricardo1991** [comment]
Except you can't tell if the site is in darkmode without this #138

**Comment by sharkykh** [comment]
@Ricardo1991 The `bootstrap-dark.min.css` file is loaded by [`setThemeDark()`](https://github.com/nyaadevs/nyaa/blob/cfa41bf3886395e157692e05ff6e226419bd0076/nyaa/static/js/main.js#L179), plus it also sets a localStorage item, `theme`, to `dark`/`light`.

**Comment by Ricardo1991** [comment]
@sharkykh I know, but is altering bootstrap-dark.min.css the best option? Hence the css class so you can just put it on main.css

**Comment by sharkykh** [comment]
@Ricardo1991 You're correct, I got confused. Obviously bootstrap shouldn't be altered.

**Comment by ReimuHakurei** [comment]
What? In this case, altering Bootstrap is the proper thing to do, though obviously we need documentation of what exact changes were put into the Bootstrap customization tool to get this result so we can make further changes later.

**Comment by thebombzen** [comment]
Success's background color was changed to #4c6442 (it was #dff0d8 previously). 
Danger's background color was changed to #988383 (it was #f2dede previously). 
A new <a> color for Success was added - #0d86ec, because the previous (default) <a> color on the new background was unreadable. 
A new <a> color for Danger was added - #105692, because the previous (default) <a> color on the new background was unreadable.

**Comment by Tsunamical** [comment]
It'd be best if you added those to the commit message as well, that way we wouldn't need to dig back to the PR to find out *exactly* what was changed.

**Comment by thebombzen** [comment]
I'll see if I can figure out how to work some git magic to make that happen

**Comment by thebombzen** [comment]
Alright, I added it to the commit message and squashed everything together. It might be a bad idea to merge this commit technically because it seems that the proper way to do this would be to add a separate case to bootstrap's `dark.css` page which currently isn't there.

**Comment by TheAMM** [comment]
#357

**Pull request closed without merging**
