### PR TITLE
replaced deprecated Classes by their newer versions

### PR DESCRIPTION
**Pull request by jprandomdev**
replaced deprecated Classes by their newer versions

### CODE REVIEW

**Comment by Tipuch** [comment]
sure no problem, I'll update this PR when #53 gets merged.

**Comment by jprandomdev** [comment]
no problem, I'll do just that once #53 gets merged.
Also yeah, point noted for the PEP8 fixes in the same commit, I noticed afterwards :(

**Comment by sharkykh** [comment]
@jprandomdev 
#53 Just go merged :)

**Comment by jprandomdev** [comment]
it should be good to go now :)

**Comment by sharkykh** [comment]
@jprandomdev That's a bit of a mess now... for some reason

**Comment by sharkykh** [comment]
@jprandomdev When you rebased, did you **force-push**? (that's what you should do)

**Comment by jprandomdev** [comment]
ah no I just pushed, sorry I'm not very used to rebasing (I've always just merged)

**Comment by sharkykh** [comment]
@jprandomdev 
I guess it's also more than that, because your first commit also changed some unrelated lines and that was messy. I'm not judging you, just telling you so you'll know for next time :)

In any case, my suggestion is this:

- Checkout your branch
- Do a **HARD reset** of your local branch to `nyaadevs/master`
- Apply this diff/patch https://gist.github.com/sharkykh/dc8609c0ded70743bf5283765ad19ff4
- Commit
- Force-Push the branch

That should fix it.

**Comment by jprandomdev** [comment]
I'll do just that this afternoon. I'll fix it. Some changes are missing from your patch but don't worry about it.

**Comment by aldacron** [comment]
Can we clean up this PR? There's a huuuuge changelist right now.

**Comment by jprandomdev** [comment]
pfiou

**Comment by jprandomdev** [comment]
Thank you for your patience.

**Pull request merged**
