### PR TITLE
[Restructure routes 4] Move user routes into blueprint

### PR DESCRIPTION
**Pull request by sharkykh**
**_Note:_ This PR is against the 'blueprints' branch.**
[4th pull request out of 8 in total]

This PR moves the following routes into the `users` blueprint (`nyaa/views/users.py`):

* /user/`<user_name>`
* /user/activate/`<payload>`

`url_for()`-s in templates and routes were updated.

This moves supporting functions and variables into other files:
* Into `nyaa.utils`:
  - `cached_function()`
  - `chain_get()`
* Into `nyaa.search`:
  - `DEFAULT_MAX_SEARCH_RESULT`
  - `DEFAULT_PER_PAGE`
  - `SERACH_PAGINATE_DISPLAY_MSG`
  - `_generate_query_string`
* Into the blueprint `nyaa.views.users`:
  - `get_serializer()`
  - `get_activation_link()`

**Notes:**
Some changes made to the master branch (https://github.com/nyaadevs/nyaa/commit/b51045503deab41e5db27caec725c9cd4b9c2f98) are not in this branch (to keep things simple).
When we open the PR from `blueprints` to `master`, it will cause conflicts, and I'll resolve them :+1: 

***

You can also use git blame to see what code was actually changed by me (and what was plainly copied)
```console
git blame -C HEAD -- nyaa/views/users.py
```

### Testing progress:
- [x] `get_serializer()`
- [x] `get_activation_link()`
- [x] GET `/user/<user_name>`
- [x] POST `/user/<user_name>` (change user level)
- [x] `/user/activate/<payload>`
- [x] `/adminlog`
- [x] GET `/reports`
- [x] POST `/reports` (perform action - close)
- [x] GET `/view/<torrent_id>/edit`
- [x] POST `/view/<torrent_id>/edit` (do edit)
- [x] GET `/view/<torrent_id>` (with comments)
- [x] POST `/view/<torrent_id>` (post comment)

### CODE REVIEW

**Comment by ReimuHakurei** [comment]
Is #295 ready to be merged?

**Comment by sharkykh** [comment]
@ReimuHakurei 
Yup!

**Comment by sharkykh** [comment]
I'll test this and #301 thoroughly tomorrow so we can merge them and continue.
The backlog is real :sweat_smile:

**Comment by sharkykh** [comment]
Done testing, progress updated.

**Pull request merged**
