### PR TITLE
static: losslessly optimise PNG images even more

### PR DESCRIPTION
**Pull request by thebombzen**
Used TruePNG and zopflipng to optimise the images even more,
saving a whopping 4073 bytes.

The optimisation is lossless, i.e. the decoded pixel values do not
change at all.

### CODE REVIEW

**Comment by TheAMM** [comment]
@CounterPillow btfo'd

**Comment by CounterPillow** [comment]
I don't think TruePNG is lossless, is it?

**Comment by thebombzen** [comment]
It is lossless, provided that you don't turn on the lossy setting (off by default).

**Comment by Arylide** [comment]
Okay.

**Comment by thebombzen** [comment]
(´・ω・｀)

**Pull request merged**
